language: python
python:
    - "2.7"

before_install:
    - pip install -r requirements_dev.txt
    - make lint

install:
    - pip install -r requirements.txt

script:
    - make unit

after_success:
    - coveralls
